# Generated by Django 4.0.1 on 2023-10-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_user', models.CharField(max_length=20)),
                ('task_status', models.CharField(max_length=15)),
            ],
        ),
    ]
